#!/bin/sh

# cd to file containing script or something?
BASEDIR=$(dirname "$0")
echo "$BASEDIR"
cd "$BASEDIR"

export DOTNET_ROOT="$(pwd)/../Resources/dotnet"

exec ../Resources/bin/SS14.Launcher "$@"
